### PR TITLE
hi

### PR DESCRIPTION
**Pull request by ghost**
the funni among us 

( sorry for making as pull request plz dont kill me )

### CODE REVIEW

**Comment by ghost** [comment]
can you guys accept this pull request please

**Review by JuniorNovoa1 — APPROVED** [review]
100% Cool *VINE BOOM

**Comment by ghost** [comment]
🤦

**Comment by Sylveondev** [comment]
Funny

**Comment by Diamantitos2** [comment]
The code is not complete i guess, There are some songs missing

**Pull request closed without merging**
